id: P3E242BD2
initial_creation_type: input
source_metadata:
  title: Vinaya
  parent: 1. Commentaries on the Eighteen Great Treatises
  source: https://sakyalibrary.com
  bases:
    8e81:
      title: དགེ་སློང་ཕའི་སོ་སོར་ཐར་པའི་མདོ་བཞུགས་སོ།།
      author: ཤཱཀྱ་ཐུབ་པ།
      base_file: 8e81.txt
      order: 1
    307a:
      title: སོ་སོར་ཐར་པའི་མདོའི་ལེགས་བཤད། འདུལ་བའི་སྡེ་སྣོད་མཛེས་པར་བྱེད་པའི་རྒྱན་ཞེས་བྱ་བ།།་་་་་མཁན་ཆེན་ནས་གྲུབ།
      author: སྤོས་ཁང་པ་རིན་ཆེན་རྒྱལ་མཚན།
      base_file: 307a.txt
      order: 2
    7a6e:
      title: འདུལ་བ་མདོ་རྩ་བ་བཞུགས་སོ།།
      author: སློབ་དཔོན་ཡོན་ཏན་འོད།
      base_file: 7a6e.txt
      order: 3
    8db2:
      title: འདུལ་ཊཱིཀ་ཉི་མའི་འོད་ཟེར་ལེགས་བཤད་ལུང་རིགས་ཀྱི་རྒྱ་མཚོ་ལས་དགེ་སློང་མའི་རྣམ་འབྱེད་ཞུ་བ་སྤྱིར་བསྟན་གཞི་སྨད་བཞུགས།།
      author: མཚོ་སྣ་བ་ཤེས་རབ་བཟང་པོ།
      base_file: 8db2.txt
      order: 4
    f085:
      title: འདུལ་བ་མདོ་རྩ་བའི་སྤྱི་དོན་ལེགས་བཤད་འོད་ཀྱི་སྣང་བ་ཚིག་དོན་རབ་གསལ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: ཀོང་སྟོན་དབང་ཕྱུག་དཔལ་བཟང་།
      base_file: f085.txt
      order: 5
    cf69:
      title: འཕགས་པ་གཞི་ཐམས་ཅད་ཡོད་པར་སྨྲ་བའི་དགེ་ཚུལ་གྱི་ཚིག་ལེའུར་བྱས་པ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: ཤཱཀྱ་འོད།
      base_file: cf69.txt
      order: 6
    7d03:
      title: དགེ་སྦྱོང་གི་ཀཱ་རི་ཀཱ་ལྔ་བཅུ་པའི་ཚིག་གི་བརྗེད་བྱང་དུ་བྱས་པ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: ཀ་མ་ལ་ཤཱི་ལ།
      base_file: 7d03.txt
      order: 7
    d3fa:
      title: འཕགས་པ་གཞི་ཐམས་ཅད་ཡོད་པར་སྨྲ་བའི་དགེ་ཚུལ་གྱི་ཚིག་ལེའུར་བྱས་པ་བཞུགས།།
      author: ཀླུ་སྒྲུབ་འམ།    དགེ་འདུན་བཟང་པོ།
      base_file: d3fa.txt
      order: 8
    fc7d:
      title: འཕགས་པ་གཞི་ཐམས་ཅད་ཡོད་པར་སྨྲ་བའི་དགེ་ཚུལ་གྱི་ཚིག་ལེའུར་བྱས་པའི་འགྲེལ་པ་འོད་ལྡན་བྱ་བ་བཞུགས་སོ།།་་་་་རང་འགྲེལ།
      author: ཤཱཀྱ་འོད།
      base_file: fc7d.txt
      order: 9
    f403:
      title: འདུལ་བ་མེ་ཏོག་ཕྲེང་རྒྱུད་ཀྱི་རྣམ་འགྲེལ་ཚིག་དོན་རབ་ཏུ་གསལ་བའི་ཉི་འོད་ཅེས་བྱ་བ་བཞུགས་སོ།།
      author: རོང་སྟོན་ཤཱཀྱ་རྒྱལ་མཚན།
      base_file: f403.txt
      order: 10
    e7a1:
      title: འདུལ་བའི་རྣམ་པར་བཤད་པ་ལུང་རིགས་ཀྱི་གཏེར་མཛོད་ཅེས་བྱ་བ་བཞུགས་སོ།།
      author: འབྲས་ཡུལ་ཀུན་དགའ་ཆོས་བཟང་།
      base_file: e7a1.txt
      order: 11
    b61f:
      title: རབ་ཏུ་བྱུང་བ་རྣམས་ཀྱི་བསླབ་བྱ་ཉམས་སུ་བླང་བའི་ཆོས་འདུལ་བ་རྒྱ་མཚོའི་སྙིང་པོ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: ཀུན་མཁྱེན་གོ་རམས་པ།
      base_file: b61f.txt
      order: 12
    67cf:
      title: ལས་བརྒྱ་རྩ་གཅིག་གི་དཀའ་གནས་སོ་སོའི་དོན་གསལ་བར་བྱེད་པའི་བསྟན་བཅོས་ཟླ་བའི་ཤིང་རྟ་ལྡེབ་བཞུགས་སོ།།
      author: ཤཱཀ་མཆོག
      base_file: 67cf.txt
      order: 13
    961a:
      title: འདུལ་བའི་སྤྱི་དོན་ཐུབ་བསྟན་རྒྱས་པའི་ཉིན་བྱེད་ཅེས་བྱ་བ་བཞུགས་སོ།།
      author: མཁན་ཆེན་ངག་ཆོས།
      base_file: 961a.txt
      order: 14
    cb83:
      title: འདུལ་བའི་ལག་ལེན་རིན་ཆེན་སྒྲོན་མེ་ཞེས་བྱ་བ་བཞུགས་སོ།།
      author: སྡེ་གཞུང་སྤྲུལ་སྐུ་ཀུན་དགའ་རྒྱལ་མཚན།
      base_file: cb83.txt
      order: 15
created_at: '2022-04-06T15:29:28.556861'
last_modified_at: '2022-04-06T15:29:28.556867'
